// Level 4 - 下界征途 Nether Journey
export const level4 = {
  name: "Nether Journey",
  nameCn: "下界征途",
  star: "⭐⭐⭐⭐",
  entities: [
    { id: "minecraft:blaze", en: "BLAZE", cn: "烈焰人", phonetic: "/bleɪz/" },
    { id: "minecraft:ghast", en: "GHAST", cn: "恶魂", phonetic: "/ɡæst/" },
    { id: "minecraft:magma_cube", en: "MAGMA CUBE", cn: "岩浆怪", phonetic: "/ˈmæɡmə kjuːb/" },
    { id: "minecraft:piglin", en: "PIGLIN", cn: "猪灵", phonetic: "/ˈpɪɡlɪn/" },
    { id: "minecraft:hoglin", en: "HOGLIN", cn: "疣猪兽", phonetic: "/ˈhɒɡlɪn/" },
    { id: "minecraft:strider", en: "STRIDER", cn: "炽足兽", phonetic: "/ˈstraɪdər/" },
    { id: "minecraft:zombified_piglin", en: "ZOMBIFIED PIGLIN", cn: "僵尸猪灵", phonetic: "/ˈzɒmbɪfaɪd ˈpɪɡlɪn/" },
    { id: "minecraft:piglin_brute", en: "PIGLIN BRUTE", cn: "猪灵蛮兵", phonetic: "/ˈpɪɡlɪn bruːt/" },
    { id: "minecraft:wither_skeleton", en: "WITHER SKELETON", cn: "凋灵骷髅", phonetic: "/ˈwɪðər ˈskelɪtən/" },
    { id: "minecraft:elder_guardian", en: "ELDER GUARDIAN", cn: "远古守卫", phonetic: "/ˈeldər ˈɡɑːrdiən/" },
  ],
  blocks: [
    { id: "minecraft:netherrack", en: "NETHERRACK", cn: "下界岩", phonetic: "/ˈneðəræk/" },
    { id: "minecraft:nether_brick", en: "NETHER BRICK", cn: "下界砖", phonetic: "/ˈneðər brɪk/" },
    { id: "minecraft:glowstone", en: "GLOWSTONE", cn: "荧石", phonetic: "/ˈɡloʊstoʊn/" },
    { id: "minecraft:magma", en: "MAGMA BLOCK", cn: "岩浆块", phonetic: "/ˈmæɡmə blɒk/" },
    { id: "minecraft:soul_soil", en: "SOUL SOIL", cn: "灵魂土", phonetic: "/soʊl sɔɪl/" },
    { id: "minecraft:warped_stem", en: "WARPED STEM", cn: "诡异菌柄", phonetic: "/wɔːrpt stem/" },
    { id: "minecraft:crimson_stem", en: "CRIMSON STEM", cn: "绯红菌柄", phonetic: "/ˈkrɪmzən stem/" },
    { id: "minecraft:warped_planks", en: "WARPED PLANKS", cn: "诡异木板", phonetic: "/wɔːrpt plæŋks/" },
    { id: "minecraft:crimson_planks", en: "CRIMSON PLANKS", cn: "绯红木板", phonetic: "/ˈkrɪmzən plæŋks/" },
    { id: "minecraft:shroomlight", en: "SHROOMLIGHT", cn: "菌光体", phonetic: "/ˈʃruːmlaɪt/" },
    { id: "minecraft:nether_gold_ore", en: "NETHER GOLD ORE", cn: "下界金矿", phonetic: "/ˈneðər ɡoʊld ɔːr/" },
    { id: "minecraft:ancient_debris", en: "ANCIENT DEBRIS", cn: "远古残骸", phonetic: "/ˈeɪnʃənt dəˈbriː/" },
    { id: "minecraft:basalt", en: "BASALT", cn: "玄武岩", phonetic: "/bəˈsɔːlt/" },
    { id: "minecraft:blackstone", en: "BLACKSTONE", cn: "黑石", phonetic: "/ˈblækstoʊn/" },
    { id: "minecraft:respawn_anchor", en: "RESPAWN ANCHOR", cn: "重生锚", phonetic: "/riːˈspɔːn ˈæŋkər/" },
    { id: "minecraft:crying_obsidian", en: "CRYING OBSIDIAN", cn: "哭泣黑曜石", phonetic: "/ˈkraɪɪŋ əbˈsɪdiən/" },
    { id: "minecraft:nether_wart", en: "NETHER WART", cn: "下界疣", phonetic: "/ˈneðər wɔːrt/" },
    { id: "minecraft:sculk", en: "SCULK", cn: "幽匿块", phonetic: "/skʌlk/" },
    { id: "minecraft:sculk_sensor", en: "SCULK SENSOR", cn: "幽匿感测器", phonetic: "/skʌlk ˈsensər/" },
    { id: "minecraft:sculk_shrieker", en: "SCULK SHRIEKER", cn: "幽匿尖啸体", phonetic: "/skʌlk ˈʃriːkər/" },
    { id: "minecraft:sculk_catalyst", en: "SCULK CATALYST", cn: "幽匿催发体", phonetic: "/skʌlk ˈkætəlɪst/" },
    { id: "minecraft:crimson_fungus", en: "CRIMSON FUNGUS", cn: "绯红菌", phonetic: "/ˈkrɪmzən ˈfʌŋɡəs/" },
    { id: "minecraft:warped_fungus", en: "WARPED FUNGUS", cn: "诡异菌", phonetic: "/wɔːrpt ˈfʌŋɡəs/" },
    { id: "minecraft:crimson_roots", en: "CRIMSON ROOTS", cn: "绯红菌索", phonetic: "/ˈkrɪmzən ruːts/" },
    { id: "minecraft:warped_roots", en: "WARPED ROOTS", cn: "诡异菌索", phonetic: "/wɔːrpt ruːts/" },
    { id: "minecraft:twisting_vines", en: "TWISTING VINES", cn: "缠怨藤", phonetic: "/ˈtwɪstɪŋ vaɪnz/" },
    { id: "minecraft:weeping_vines", en: "WEEPING VINES", cn: "垂泪藤", phonetic: "/ˈwiːpɪŋ vaɪnz/" },
    { id: "minecraft:nether_sprouts", en: "NETHER SPROUTS", cn: "下界苗", phonetic: "/ˈneðər spraʊts/" },
    { id: "minecraft:gilded_blackstone", en: "GILDED BLACKSTONE", cn: "镶金黑石", phonetic: "/ˈɡɪldɪd ˈblækstoʊn/" },
    { id: "minecraft:quartz_block", en: "QUARTZ", cn: "石英", phonetic: "/kwɔːrts/" },
    { id: "minecraft:soul_campfire", en: "SOUL CAMPFIRE", cn: "灵魂营火", phonetic: "/soʊl ˈkæmpfaɪər/" },
    { id: "minecraft:polished_basalt", en: "POLISHED BASALT", cn: "磨制玄武岩", phonetic: "/ˈpɒlɪʃt bəˈsɔːlt/" },
    { id: "minecraft:polished_blackstone", en: "POLISHED BLACKSTONE", cn: "磨制黑石", phonetic: "/ˈpɒlɪʃt ˈblækstoʊn/" },
    { id: "minecraft:warp_wart_block", en: "WARPED WART BLOCK", cn: "诡异疣块", phonetic: "/wɔːrpt wɔːrt blɒk/" },
    { id: "minecraft:nether_wart_block", en: "NETHER WART BLOCK", cn: "下界疣块", phonetic: "/ˈneðər wɔːrt blɒk/" },
  ],
  items: [
    { id: "minecraft:netherite_sword", en: "NETHERITE SWORD", cn: "下界合金剑", phonetic: "/ˈneðəraɪt sɔːrd/" },
    { id: "minecraft:netherite_pickaxe", en: "NETHERITE PICKAXE", cn: "下界合金镐", phonetic: "/ˈneðəraɪt ˈpɪkæks/" },
    { id: "minecraft:netherite_axe", en: "NETHERITE AXE", cn: "下界合金斧", phonetic: "/ˈneðəraɪt æks/" },
    { id: "minecraft:netherite_helmet", en: "NETHERITE HELMET", cn: "下界合金头盔", phonetic: "/ˈneðəraɪt ˈhelmɪt/" },
    { id: "minecraft:netherite_chestplate", en: "NETHERITE CHESTPLATE", cn: "下界合金胸甲", phonetic: "/ˈneðəraɪt ˈtʃestpleɪt/" },
    { id: "minecraft:netherite_leggings", en: "NETHERITE LEGGINGS", cn: "下界合金护腿", phonetic: "/ˈneðəraɪt ˈleɡɪŋz/" },
    { id: "minecraft:netherite_boots", en: "NETHERITE BOOTS", cn: "下界合金靴子", phonetic: "/ˈneðəraɪt buːts/" },
    { id: "minecraft:blaze_rod", en: "BLAZE ROD", cn: "烈焰棒", phonetic: "/bleɪz rɒd/" },
    { id: "minecraft:blaze_powder", en: "BLAZE POWDER", cn: "烈焰粉", phonetic: "/bleɪz ˈpaʊdər/" },
    { id: "minecraft:nether_star", en: "NETHER STAR", cn: "下界之星", phonetic: "/ˈneðər stɑːr/" },
    { id: "minecraft:ghast_tear", en: "GHAST TEAR", cn: "恶魂之泪", phonetic: "/ɡæst tɪr/" },
    { id: "minecraft:magma_cream", en: "MAGMA CREAM", cn: "岩浆膏", phonetic: "/ˈmæɡmə kriːm/" },
    { id: "minecraft:netherite_ingot", en: "NETHERITE INGOT", cn: "下界合金锭", phonetic: "/ˈneðəraɪt ˈɪŋɡət/" },
    { id: "minecraft:netherite_scrap", en: "NETHERITE SCRAP", cn: "下界合金碎片", phonetic: "/ˈneðəraɪt skræp/" },
    { id: "minecraft:gold_nugget", en: "GOLD NUGGET", cn: "金粒", phonetic: "/ɡoʊld ˈnʌɡɪt/" },
    { id: "minecraft:soul_lantern", en: "SOUL LANTERN", cn: "灵魂灯笼", phonetic: "/soʊl ˈlæntərn/" },
    { id: "minecraft:warped_fungus_on_a_stick", en: "WARPED FUNGUS ON A STICK", cn: "诡异菌钓竿", phonetic: "/wɔːrpt ˈfʌŋɡəs ɒn ə stɪk/" },
    { id: "minecraft:fire_charge", en: "FIRE CHARGE", cn: "火焰弹", phonetic: "/faɪər tʃɑːrdʒ/" },
    { id: "minecraft:ender_eye", en: "EYE OF ENDER", cn: "末影之眼", phonetic: "/aɪ əv ˈendər/" },
    { id: "minecraft:wither_skeleton_skull", en: "WITHER SKULL", cn: "凋灵骷髅头", phonetic: "/ˈwɪðər skʌl/" },
    { id: "minecraft:armor_trim_smithing_template", en: "SMITHING TEMPLATE", cn: "锻造模板", phonetic: "/ˈsmɪθɪŋ ˈtempleɪt/" },
    { id: "minecraft:lodestone_compass", en: "LODESTONE COMPASS", cn: "磁石指针", phonetic: "/ˈloʊdstoʊn ˈkʌmpəs/" },
    { id: "minecraft:spectral_arrow", en: "SPECTRAL ARROW", cn: "光灵箭", phonetic: "/ˈspektrəl ˈæroʊ/" },
    { id: "minecraft:soul_torch", en: "SOUL TORCH", cn: "灵魂火把", phonetic: "/soʊl tɔːrtʃ/" },
    { id: "minecraft:warped_door", en: "WARPED DOOR", cn: "诡异门", phonetic: "/wɔːrpt dɔːr/" },
  ],
};
