// Level 3 - 矿工之路 Miner's Path
export const level3 = {
  name: "Miner's Path",
  nameCn: "矿工之路",
  star: "⭐⭐⭐",
  entities: [
    { id: "minecraft:minecart", en: "MINECART", cn: "矿车", phonetic: "/ˈmaɪnkɑːrt/" },
    { id: "minecraft:llama", en: "LLAMA", cn: "羊驼", phonetic: "/ˈlɑːmə/" },
    { id: "minecraft:mule", en: "MULE", cn: "骡子", phonetic: "/mjuːl/" },
    { id: "minecraft:wandering_trader", en: "TRADER", cn: "商人", phonetic: "/ˈtreɪdər/" },
    { id: "minecraft:snow_golem", en: "SNOW GOLEM", cn: "雪傀儡", phonetic: "/snoʊ ˈɡoʊləm/" },
  ],
  blocks: [
    { id: "minecraft:iron_ore", en: "IRON ORE", cn: "铁矿石", phonetic: "/ˈaɪərn ɔːr/" },
    { id: "minecraft:gold_ore", en: "GOLD ORE", cn: "金矿石", phonetic: "/ɡoʊld ɔːr/" },
    { id: "minecraft:diamond_ore", en: "DIAMOND ORE", cn: "钻石矿", phonetic: "/ˈdaɪmənd ɔːr/" },
    { id: "minecraft:coal_ore", en: "COAL ORE", cn: "煤矿石", phonetic: "/koʊl ɔːr/" },
    { id: "minecraft:copper_ore", en: "COPPER ORE", cn: "铜矿石", phonetic: "/ˈkɒpər ɔːr/" },
    { id: "minecraft:redstone_ore", en: "REDSTONE ORE", cn: "红石矿", phonetic: "/ˈredˌstoʊn ɔːr/" },
    { id: "minecraft:lapis_ore", en: "LAPIS ORE", cn: "青金石矿", phonetic: "/ˈlæpɪs ɔːr/" },
    { id: "minecraft:emerald_ore", en: "EMERALD ORE", cn: "绿宝石矿", phonetic: "/ˈemərəld ɔːr/" },
    { id: "minecraft:deepslate", en: "DEEPSLATE", cn: "深板岩", phonetic: "/ˈdiːpsleɪt/" },
    { id: "minecraft:obsidian", en: "OBSIDIAN", cn: "黑曜石", phonetic: "/əbˈsɪdiən/" },
    { id: "minecraft:iron_block", en: "IRON BLOCK", cn: "铁块", phonetic: "/ˈaɪərn blɒk/" },
    { id: "minecraft:gold_block", en: "GOLD BLOCK", cn: "金块", phonetic: "/ɡoʊld blɒk/" },
    { id: "minecraft:diamond_block", en: "DIAMOND BLOCK", cn: "钻石块", phonetic: "/ˈdaɪmənd blɒk/" },
    { id: "minecraft:anvil", en: "ANVIL", cn: "铁砧", phonetic: "/ˈænvɪl/" },
    { id: "minecraft:rail", en: "RAIL", cn: "铁轨", phonetic: "/reɪl/" },
    { id: "minecraft:brick_block", en: "BRICK", cn: "砖块", phonetic: "/brɪk/" },
    { id: "minecraft:mossy_cobblestone", en: "MOSSY STONE", cn: "苔石", phonetic: "/ˈmɒsi stoʊn/" },
    { id: "minecraft:stonebrick", en: "STONE BRICK", cn: "石砖", phonetic: "/stoʊn brɪk/" },
    { id: "minecraft:grindstone", en: "GRINDSTONE", cn: "砂轮", phonetic: "/ˈɡraɪndstoʊn/" },
    { id: "minecraft:smithing_table", en: "SMITHING TABLE", cn: "锻造台", phonetic: "/ˈsmɪθɪŋ ˈteɪbl/" },
    { id: "minecraft:blast_furnace", en: "BLAST FURNACE", cn: "高炉", phonetic: "/blæst ˈfɜːrnɪs/" },
    { id: "minecraft:stonecutter_block", en: "STONECUTTER", cn: "切石机", phonetic: "/ˈstoʊnˌkʌtər/" },
    { id: "minecraft:lantern", en: "LANTERN", cn: "灯笼", phonetic: "/ˈlæntərn/" },
    { id: "minecraft:barrel", en: "BARREL", cn: "木桶", phonetic: "/ˈbærəl/" },
  ],
};
