// Level 1 - 第一天 First Day
export const level1 = {
  name: "First Day",
  nameCn: "第一天",
  star: "⭐",
  entities: [
    { id: "minecraft:cow", en: "COW", cn: "奶牛", phonetic: "/kaʊ/" },
    { id: "minecraft:pig", en: "PIG", cn: "猪", phonetic: "/pɪɡ/" },
    { id: "minecraft:sheep", en: "SHEEP", cn: "绵羊", phonetic: "/ʃiːp/" },
    { id: "minecraft:chicken", en: "CHICKEN", cn: "鸡", phonetic: "/ˈtʃɪkɪn/" },
    { id: "minecraft:horse", en: "HORSE", cn: "马", phonetic: "/hɔːrs/" },
    { id: "minecraft:donkey", en: "DONKEY", cn: "驴", phonetic: "/ˈdɒŋki/" },
    { id: "minecraft:cat", en: "CAT", cn: "猫", phonetic: "/kæt/" },
    { id: "minecraft:wolf", en: "WOLF", cn: "狼", phonetic: "/wʊlf/" },
    { id: "minecraft:rabbit", en: "RABBIT", cn: "兔子", phonetic: "/ˈræbɪt/" },
    { id: "minecraft:bee", en: "BEE", cn: "蜜蜂", phonetic: "/biː/" },
    { id: "minecraft:bat", en: "BAT", cn: "蝙蝠", phonetic: "/bæt/" },
    { id: "minecraft:squid", en: "SQUID", cn: "鱿鱼", phonetic: "/skwɪd/" },
    { id: "minecraft:cod", en: "COD", cn: "鳕鱼", phonetic: "/kɒd/" },
    { id: "minecraft:zombie", en: "ZOMBIE", cn: "僵尸", phonetic: "/ˈzɒmbi/" },
    { id: "minecraft:skeleton", en: "SKELETON", cn: "骷髅", phonetic: "/ˈskelɪtən/" },
    { id: "minecraft:spider", en: "SPIDER", cn: "蜘蛛", phonetic: "/ˈspaɪdər/" },
    { id: "minecraft:creeper", en: "CREEPER", cn: "苦力怕", phonetic: "/ˈkriːpər/" },
  ],
  blocks: [
    { id: "minecraft:dirt", en: "DIRT", cn: "泥土", phonetic: "/dɜːrt/" },
    { id: "minecraft:grass_block", en: "GRASS", cn: "草方块", phonetic: "/ɡræs/" },
    { id: "minecraft:stone", en: "STONE", cn: "石头", phonetic: "/stoʊn/" },
    { id: "minecraft:cobblestone", en: "COBBLESTONE", cn: "圆石", phonetic: "/ˈkɒblstoʊn/" },
    { id: "minecraft:sand", en: "SAND", cn: "沙子", phonetic: "/sænd/" },
    { id: "minecraft:gravel", en: "GRAVEL", cn: "砂砾", phonetic: "/ˈɡrævəl/" },
    { id: "minecraft:oak_log", en: "OAK LOG", cn: "橡木原木", phonetic: "/oʊk lɒɡ/" },
    { id: "minecraft:oak_planks", en: "OAK PLANKS", cn: "橡木板", phonetic: "/oʊk plæŋks/" },
    { id: "minecraft:crafting_table", en: "CRAFTING TABLE", cn: "工作台", phonetic: "/ˈkræftɪŋ ˈteɪbl/" },
    { id: "minecraft:furnace", en: "FURNACE", cn: "熔炉", phonetic: "/ˈfɜːrnɪs/" },
    { id: "minecraft:chest", en: "CHEST", cn: "箱子", phonetic: "/tʃest/" },
    { id: "minecraft:torch", en: "TORCH", cn: "火把", phonetic: "/tɔːrtʃ/" },
    { id: "minecraft:bed", en: "BED", cn: "床", phonetic: "/bed/" },
    { id: "minecraft:door", en: "DOOR", cn: "门", phonetic: "/dɔːr/" },
    { id: "minecraft:ladder", en: "LADDER", cn: "梯子", phonetic: "/ˈlædər/" },
    { id: "minecraft:glass", en: "GLASS", cn: "玻璃", phonetic: "/ɡlæs/" },
    { id: "minecraft:fence", en: "FENCE", cn: "栅栏", phonetic: "/fens/" },
    { id: "minecraft:red_flower", en: "FLOWER", cn: "花", phonetic: "/flaʊər/" },
    { id: "minecraft:brown_mushroom", en: "MUSHROOM", cn: "蘑菇", phonetic: "/ˈmʌʃruːm/" },
    { id: "minecraft:sugarcane", en: "SUGAR CANE", cn: "甘蔗", phonetic: "/ˈʃʊɡər keɪn/" },
    { id: "minecraft:wheat", en: "WHEAT", cn: "小麦", phonetic: "/wiːt/" },
    { id: "minecraft:pumpkin", en: "PUMPKIN", cn: "南瓜", phonetic: "/ˈpʌmpkɪn/" },
    { id: "minecraft:leaves", en: "LEAVES", cn: "树叶", phonetic: "/liːvz/" },
    { id: "minecraft:water", en: "WATER", cn: "水", phonetic: "/ˈwɔːtər/" },
    { id: "minecraft:lava", en: "LAVA", cn: "岩浆", phonetic: "/ˈlɑːvə/" },
    { id: "minecraft:coal_ore", en: "COAL ORE", cn: "煤矿石", phonetic: "/koʊl ɔːr/" },
    { id: "minecraft:iron_ore", en: "IRON ORE", cn: "铁矿石", phonetic: "/ˈaɪərn ɔːr/" },
    { id: "minecraft:copper_ore", en: "COPPER ORE", cn: "铜矿石", phonetic: "/ˈkɒpər ɔːr/" },
    { id: "minecraft:farmland", en: "FARMLAND", cn: "耕地", phonetic: "/ˈfɑːrmlænd/" },
    { id: "minecraft:trapdoor", en: "TRAPDOOR", cn: "活板门", phonetic: "/ˈtræpdɔːr/" },
    { id: "minecraft:slab", en: "SLAB", cn: "台阶", phonetic: "/slæb/" },
    { id: "minecraft:stairs", en: "STAIRS", cn: "楼梯", phonetic: "/stɛrz/" },
    { id: "minecraft:sign", en: "SIGN", cn: "告示牌", phonetic: "/saɪn/" },
    { id: "minecraft:wool", en: "WOOL", cn: "羊毛", phonetic: "/wʊl/" },
    { id: "minecraft:carpet", en: "CARPET", cn: "地毯", phonetic: "/ˈkɑːrpɪt/" },
    { id: "minecraft:painting", en: "PAINTING", cn: "画", phonetic: "/ˈpeɪntɪŋ/" },
    { id: "minecraft:flower_pot", en: "FLOWER POT", cn: "花盆", phonetic: "/flaʊər pɒt/" },
    { id: "minecraft:fern", en: "FERN", cn: "蕨", phonetic: "/fɜːrn/" },
    { id: "minecraft:beetroot", en: "BEETROOT", cn: "甜菜", phonetic: "/ˈbiːtruːt/" },
    { id: "minecraft:mud", en: "MUD", cn: "泥巴", phonetic: "/mʌd/" },
    { id: "minecraft:sandstone", en: "SANDSTONE", cn: "砂岩", phonetic: "/ˈsændstoʊn/" },
    { id: "minecraft:seagrass", en: "SEAGRASS", cn: "海草", phonetic: "/ˈsiːɡræs/" },
    { id: "minecraft:kelp", en: "KELP", cn: "海带", phonetic: "/kelp/" },
    { id: "minecraft:moss_carpet", en: "MOSS CARPET", cn: "苔藓地毯", phonetic: "/mɒs ˈkɑːrpɪt/" },
    { id: "minecraft:clay", en: "CLAY", cn: "粘土块", phonetic: "/kleɪ/" },
  ],
  items: [
    { id: "minecraft:wooden_sword", en: "WOODEN SWORD", cn: "木剑", phonetic: "/ˈwʊdən sɔːrd/" },
    { id: "minecraft:wooden_pickaxe", en: "WOODEN PICKAXE", cn: "木镐", phonetic: "/ˈwʊdən ˈpɪkæks/" },
    { id: "minecraft:wooden_axe", en: "WOODEN AXE", cn: "木斧", phonetic: "/ˈwʊdən æks/" },
    { id: "minecraft:wooden_shovel", en: "WOODEN SHOVEL", cn: "木锹", phonetic: "/ˈwʊdən ˈʃʌvəl/" },
    { id: "minecraft:wooden_hoe", en: "WOODEN HOE", cn: "木锄", phonetic: "/ˈwʊdən hoʊ/" },
    { id: "minecraft:stone_sword", en: "STONE SWORD", cn: "石剑", phonetic: "/stoʊn sɔːrd/" },
    { id: "minecraft:stone_pickaxe", en: "STONE PICKAXE", cn: "石镐", phonetic: "/stoʊn ˈpɪkæks/" },
    { id: "minecraft:stone_axe", en: "STONE AXE", cn: "石斧", phonetic: "/stoʊn æks/" },
    { id: "minecraft:apple", en: "APPLE", cn: "苹果", phonetic: "/ˈæpl/" },
    { id: "minecraft:bread", en: "BREAD", cn: "面包", phonetic: "/bred/" },
    { id: "minecraft:stick", en: "STICK", cn: "木棍", phonetic: "/stɪk/" },
    { id: "minecraft:coal", en: "COAL", cn: "煤炭", phonetic: "/koʊl/" },
    { id: "minecraft:bone", en: "BONE", cn: "骨头", phonetic: "/boʊn/" },
    { id: "minecraft:arrow", en: "ARROW", cn: "箭", phonetic: "/ˈæroʊ/" },
    { id: "minecraft:bow", en: "BOW", cn: "弓", phonetic: "/baʊ/" },
    { id: "minecraft:shield", en: "SHIELD", cn: "盾牌", phonetic: "/ʃiːld/" },
    { id: "minecraft:leather", en: "LEATHER", cn: "皮革", phonetic: "/ˈleðər/" },
    { id: "minecraft:string", en: "STRING", cn: "线", phonetic: "/strɪŋ/" },
    { id: "minecraft:feather", en: "FEATHER", cn: "羽毛", phonetic: "/ˈfeðər/" },
    { id: "minecraft:egg", en: "EGG", cn: "鸡蛋", phonetic: "/eɡ/" },
    { id: "minecraft:wheat_seeds", en: "SEEDS", cn: "种子", phonetic: "/siːdz/" },
    { id: "minecraft:bucket", en: "BUCKET", cn: "桶", phonetic: "/ˈbʌkɪt/" },
    { id: "minecraft:carrot", en: "CARROT", cn: "胡萝卜", phonetic: "/ˈkærət/" },
    { id: "minecraft:potato", en: "POTATO", cn: "马铃薯", phonetic: "/pəˈteɪtoʊ/" },
    { id: "minecraft:melon_slice", en: "MELON SLICE", cn: "西瓜片", phonetic: "/ˈmelən slaɪs/" },
    { id: "minecraft:sweet_berries", en: "SWEET BERRIES", cn: "甜浆果", phonetic: "/swiːt ˈberiz/" },
    { id: "minecraft:mushroom_stew", en: "MUSHROOM STEW", cn: "蘑菇煲", phonetic: "/ˈmʌʃruːm stjuː/" },
    { id: "minecraft:raw_beef", en: "RAW BEEF", cn: "生牛肉", phonetic: "/rɔː biːf/" },
    { id: "minecraft:raw_porkchop", en: "RAW PORKCHOP", cn: "生猪排", phonetic: "/rɔː ˈpɔːrktʃɒp/" },
    { id: "minecraft:raw_chicken", en: "RAW CHICKEN", cn: "生鸡肉", phonetic: "/rɔː ˈtʃɪkɪn/" },
    { id: "minecraft:flint", en: "FLINT", cn: "燧石", phonetic: "/flɪnt/" },
    { id: "minecraft:charcoal", en: "CHARCOAL", cn: "木炭", phonetic: "/ˈtʃɑːrkoʊl/" },
    { id: "minecraft:rotten_flesh", en: "ROTTEN FLESH", cn: "腐肉", phonetic: "/ˈrɒtən fleʃ/" },
    { id: "minecraft:gunpowder", en: "GUNPOWDER", cn: "火药", phonetic: "/ˈɡʌnpaʊdər/" },
  ],
};
