// Level 5 - 大师工坊 Master Workshop
export const level5 = {
  name: "Master Workshop",
  nameCn: "大师工坊",
  star: "⭐⭐⭐⭐⭐",
  entities: [
    { id: "minecraft:wither_skeleton", en: "WITHER SKELETON", cn: "凋灵骷髅", phonetic: "/ˈwɪðər ˈskelɪtən/" },
    { id: "minecraft:blaze", en: "BLAZE", cn: "烈焰人", phonetic: "/bleɪz/" },
    { id: "minecraft:ghast", en: "GHAST", cn: "恶魂", phonetic: "/ɡæst/" },
    { id: "minecraft:magma_cube", en: "MAGMA CUBE", cn: "岩浆怪", phonetic: "/ˈmæɡmə kjuːb/" },
    { id: "minecraft:piglin", en: "PIGLIN", cn: "猪灵", phonetic: "/ˈpɪɡlɪn/" },
    { id: "minecraft:hoglin", en: "HOGLIN", cn: "疣猪兽", phonetic: "/ˈhɒɡlɪn/" },
    { id: "minecraft:strider", en: "STRIDER", cn: "炽足兽", phonetic: "/ˈstraɪdər/" },
    { id: "minecraft:shulker", en: "SHULKER", cn: "潜影贝", phonetic: "/ˈʃʌlkər/" },
    { id: "minecraft:allay", en: "ALLAY", cn: "悦灵", phonetic: "/əˈleɪ/" },
    { id: "minecraft:warden", en: "WARDEN", cn: "监守者", phonetic: "/ˈwɔːrdən/" },
    { id: "minecraft:elder_guardian", en: "ELDER GUARDIAN", cn: "远古守卫", phonetic: "/ˈeldər ˈɡɑːrdiən/" },
    { id: "minecraft:endermite", en: "ENDERMITE", cn: "末影螨", phonetic: "/ˈendərmaɪt/" },
  ],
  blocks: [
    { id: "minecraft:piston", en: "PISTON", cn: "活塞", phonetic: "/ˈpɪstən/" },
    { id: "minecraft:sticky_piston", en: "STICKY PISTON", cn: "粘性活塞", phonetic: "/ˈstɪki ˈpɪstən/" },
    { id: "minecraft:redstone_block", en: "REDSTONE BLOCK", cn: "红石块", phonetic: "/ˈredˌstoʊn blɒk/" },
    { id: "minecraft:repeater", en: "REPEATER", cn: "中继器", phonetic: "/rɪˈpiːtər/" },
    { id: "minecraft:comparator", en: "COMPARATOR", cn: "比较器", phonetic: "/kəmˈpærətər/" },
    { id: "minecraft:observer", en: "OBSERVER", cn: "侦测器", phonetic: "/əbˈzɜːrvər/" },
    { id: "minecraft:hopper", en: "HOPPER", cn: "漏斗", phonetic: "/ˈhɒpər/" },
    { id: "minecraft:dropper", en: "DROPPER", cn: "投掷器", phonetic: "/ˈdrɒpər/" },
    { id: "minecraft:dispenser", en: "DISPENSER", cn: "发射器", phonetic: "/dɪˈspensər/" },
    { id: "minecraft:daylight_detector", en: "DAYLIGHT SENSOR", cn: "阳光传感器", phonetic: "/ˈdeɪlaɪt ˈsensər/" },
    { id: "minecraft:netherrack", en: "NETHERRACK", cn: "下界岩", phonetic: "/ˈneðəræk/" },
    { id: "minecraft:nether_brick", en: "NETHER BRICK", cn: "下界砖", phonetic: "/ˈneðər brɪk/" },
    { id: "minecraft:glowstone", en: "GLOWSTONE", cn: "荧石", phonetic: "/ˈɡloʊstoʊn/" },
    { id: "minecraft:end_bricks", en: "END BRICK", cn: "末地砖", phonetic: "/end brɪk/" },
    { id: "minecraft:purpur_block", en: "PURPUR BLOCK", cn: "紫珀块", phonetic: "/ˈpɜːrpər blɒk/" },
    { id: "minecraft:sea_lantern", en: "SEA LANTERN", cn: "海晶灯", phonetic: "/siː ˈlæntərn/" },
    { id: "minecraft:conduit", en: "CONDUIT", cn: "潮涌核心", phonetic: "/ˈkɒndjuɪt/" },
    { id: "minecraft:beacon", en: "BEACON", cn: "信标", phonetic: "/ˈbiːkən/" },
    { id: "minecraft:lodestone", en: "LODESTONE", cn: "磁石", phonetic: "/ˈloʊdstoʊn/" },
    { id: "minecraft:sculk_sensor", en: "SCULK SENSOR", cn: "幽匿感测器", phonetic: "/skʌlk ˈsensər/" },
  ],
};
