// Level 5 - 终末之地 The End
export const level5 = {
  name: "The End",
  nameCn: "终末之地",
  star: "⭐⭐⭐⭐⭐",
  entities: [
    { id: "minecraft:ender_dragon", en: "ENDER DRAGON", cn: "末影龙", phonetic: "/ˈendər ˈdræɡən/" },
    { id: "minecraft:shulker", en: "SHULKER", cn: "潜影贝", phonetic: "/ˈʃʌlkər/" },
    { id: "minecraft:endermite", en: "ENDERMITE", cn: "末影螨", phonetic: "/ˈendərmaɪt/" },
    { id: "minecraft:allay", en: "ALLAY", cn: "悦灵", phonetic: "/əˈleɪ/" },
    { id: "minecraft:warden", en: "WARDEN", cn: "监守者", phonetic: "/ˈwɔːrdən/" },
    { id: "minecraft:wither", en: "WITHER", cn: "凋灵", phonetic: "/ˈwɪðər/" },
    { id: "minecraft:breeze", en: "BREEZE", cn: "旋风人", phonetic: "/briːz/" },
  ],
  blocks: [
    { id: "minecraft:end_stone", en: "END STONE", cn: "末地石", phonetic: "/end stoʊn/" },
    { id: "minecraft:end_bricks", en: "END BRICK", cn: "末地砖", phonetic: "/end brɪk/" },
    { id: "minecraft:purpur_block", en: "PURPUR BLOCK", cn: "紫珀块", phonetic: "/ˈpɜːrpər blɒk/" },
    { id: "minecraft:end_rod", en: "END ROD", cn: "末地烛", phonetic: "/end rɒd/" },
    { id: "minecraft:dragon_egg", en: "DRAGON EGG", cn: "龙蛋", phonetic: "/ˈdræɡən eɡ/" },
    { id: "minecraft:chorus_plant", en: "CHORUS PLANT", cn: "紫颂植物", phonetic: "/ˈkɔːrəs plænt/" },
    { id: "minecraft:chorus_flower", en: "CHORUS FLOWER", cn: "紫颂花", phonetic: "/ˈkɔːrəs flaʊər/" },
    { id: "minecraft:beacon", en: "BEACON", cn: "信标", phonetic: "/ˈbiːkən/" },
    { id: "minecraft:conduit", en: "CONDUIT", cn: "潮涌核心", phonetic: "/ˈkɒndjuɪt/" },
    { id: "minecraft:lodestone", en: "LODESTONE", cn: "磁石", phonetic: "/ˈloʊdstoʊn/" },
    { id: "minecraft:emerald_block", en: "EMERALD BLOCK", cn: "绿宝石块", phonetic: "/ˈemərəld blɒk/" },
    { id: "minecraft:netherite_block", en: "NETHERITE BLOCK", cn: "下界合金块", phonetic: "/ˈneðəraɪt blɒk/" },
    { id: "minecraft:shulker_box", en: "SHULKER BOX", cn: "潜影盒", phonetic: "/ˈʃʌlkər bɒks/" },
    { id: "minecraft:reinforced_deepslate", en: "REINFORCED DEEPSLATE", cn: "强化深板岩", phonetic: "/ˌriːɪnˈfɔːrst ˈdiːpsleɪt/" },
    { id: "minecraft:heavy_core", en: "HEAVY CORE", cn: "重质核心", phonetic: "/ˈhevi kɔːr/" },
    { id: "minecraft:vault", en: "VAULT", cn: "宝库", phonetic: "/vɔːlt/" },
    { id: "minecraft:trial_spawner", en: "TRIAL SPAWNER", cn: "试炼刷怪笼", phonetic: "/ˈtraɪəl ˈspɔːnər/" },
    { id: "minecraft:copper_bulb", en: "COPPER BULB", cn: "铜灯泡", phonetic: "/ˈkɒpər bʌlb/" },
    { id: "minecraft:copper_grate", en: "COPPER GRATE", cn: "铜栅", phonetic: "/ˈkɒpər ɡreɪt/" },
    { id: "minecraft:crafter", en: "CRAFTER", cn: "合成器", phonetic: "/ˈkræftər/" },
    { id: "minecraft:tinted_glass", en: "TINTED GLASS", cn: "遮光玻璃", phonetic: "/ˈtɪntɪd ɡlæs/" },
    { id: "minecraft:purpur_pillar", en: "PURPUR PILLAR", cn: "竖纹紫珀块", phonetic: "/ˈpɜːrpər ˈpɪlər/" },
    { id: "minecraft:copper_door", en: "COPPER DOOR", cn: "铜门", phonetic: "/ˈkɒpər dɔːr/" },
    { id: "minecraft:copper_trapdoor", en: "COPPER TRAPDOOR", cn: "铜活板门", phonetic: "/ˈkɒpər ˈtræpdɔːr/" },
  ],
  items: [
    { id: "minecraft:elytra", en: "ELYTRA", cn: "鞘翅", phonetic: "/ˈelɪtrə/" },
    { id: "minecraft:totem_of_undying", en: "TOTEM OF UNDYING", cn: "不死图腾", phonetic: "/ˈtoʊtəm əv ʌnˈdaɪɪŋ/" },
    { id: "minecraft:end_crystal", en: "END CRYSTAL", cn: "末影水晶", phonetic: "/end ˈkrɪstl/" },
    { id: "minecraft:chorus_fruit", en: "CHORUS FRUIT", cn: "紫颂果", phonetic: "/ˈkɔːrəs fruːt/" },
    { id: "minecraft:dragon_breath", en: "DRAGON BREATH", cn: "龙息", phonetic: "/ˈdræɡən breθ/" },
    { id: "minecraft:firework_rocket", en: "FIREWORK ROCKET", cn: "烟花火箭", phonetic: "/ˈfaɪərwɜːrk ˈrɒkɪt/" },
    { id: "minecraft:recovery_compass", en: "RECOVERY COMPASS", cn: "追溯指南针", phonetic: "/rɪˈkʌvəri ˈkʌmpəs/" },
    { id: "minecraft:echo_shard", en: "ECHO SHARD", cn: "回响碎片", phonetic: "/ˈekoʊ ʃɑːrd/" },
    { id: "minecraft:disc_fragment_5", en: "DISC FRAGMENT", cn: "唱片碎片", phonetic: "/dɪsk ˈfræɡmənt/" },
    { id: "minecraft:heart_of_the_sea", en: "HEART OF THE SEA", cn: "海洋之心", phonetic: "/hɑːrt əv ðə siː/" },
    { id: "minecraft:nautilus_shell", en: "NAUTILUS SHELL", cn: "鹦鹉螺壳", phonetic: "/ˈnɔːtɪləs ʃel/" },
    { id: "minecraft:turtle_helmet", en: "TURTLE HELMET", cn: "海龟壳头盔", phonetic: "/ˈtɜːrtl ˈhelmɪt/" },
    { id: "minecraft:mace", en: "MACE", cn: "锤", phonetic: "/meɪs/" },
    { id: "minecraft:wind_charge", en: "WIND CHARGE", cn: "风弹", phonetic: "/wɪnd tʃɑːrdʒ/" },
    { id: "minecraft:trial_key", en: "TRIAL KEY", cn: "试炼钥匙", phonetic: "/ˈtraɪəl kiː/" },
    { id: "minecraft:ominous_trial_key", en: "OMINOUS TRIAL KEY", cn: "不祥试炼钥匙", phonetic: "/ˈɒmɪnəs ˈtraɪəl kiː/" },
    { id: "minecraft:ominous_bottle", en: "OMINOUS BOTTLE", cn: "不祥之瓶", phonetic: "/ˈɒmɪnəs ˈbɒtl/" },
    { id: "minecraft:wolf_armor", en: "WOLF ARMOR", cn: "狼铠", phonetic: "/wʊlf ˈɑːrmər/" },
    { id: "minecraft:shulker_shell", en: "SHULKER SHELL", cn: "潜影壳", phonetic: "/ˈʃʌlkər ʃel/" },
    { id: "minecraft:music_disc_pigstep", en: "MUSIC DISC", cn: "音乐唱片", phonetic: "/ˈmjuːzɪk dɪsk/" },
    { id: "minecraft:globe_banner_pattern", en: "GLOBE BANNER PATTERN", cn: "地球旗帜图案", phonetic: "/ɡloʊb ˈbænər ˈpætərn/" },
    { id: "minecraft:creeper_banner_pattern", en: "CREEPER BANNER PATTERN", cn: "苦力怕旗帜图案", phonetic: "/ˈkriːpər ˈbænər ˈpætərn/" },
    { id: "minecraft:spire_armor_trim_smithing_template", en: "SPIRE ARMOR TRIM", cn: "尖塔纹饰", phonetic: "/spaɪər ˈɑːrmər trɪm/" },
    { id: "minecraft:eye_armor_trim_smithing_template", en: "EYE ARMOR TRIM", cn: "眼之纹饰", phonetic: "/aɪ ˈɑːrmər trɪm/" },
  ],
};
