// Level 1 - 农场生活 Farm Life (入门)
export const level1 = {
  name: "Farm Life",
  nameCn: "农场生活",
  star: "⭐",
  entities: [
    { id: "minecraft:cow", en: "COW", cn: "奶牛", phonetic: "/kaʊ/" },
    { id: "minecraft:pig", en: "PIG", cn: "猪", phonetic: "/pɪɡ/" },
    { id: "minecraft:sheep", en: "SHEEP", cn: "绵羊", phonetic: "/ʃiːp/" },
    { id: "minecraft:chicken", en: "CHICKEN", cn: "鸡", phonetic: "/ˈtʃɪkɪn/" },
    { id: "minecraft:horse", en: "HORSE", cn: "马", phonetic: "/hɔːrs/" },
    { id: "minecraft:donkey", en: "DONKEY", cn: "驴", phonetic: "/ˈdɒŋki/" },
    { id: "minecraft:cat", en: "CAT", cn: "猫", phonetic: "/kæt/" },
    { id: "minecraft:wolf", en: "WOLF", cn: "狼", phonetic: "/wʊlf/" },
    { id: "minecraft:villager_v2", en: "VILLAGER", cn: "村民", phonetic: "/ˈvɪlɪdʒər/" },
    { id: "minecraft:iron_golem", en: "IRON GOLEM", cn: "铁傀儡", phonetic: "/ˈaɪərn ˈɡoʊləm/" },
  ],
  blocks: [
    { id: "minecraft:dirt", en: "DIRT", cn: "泥土", phonetic: "/dɜːrt/" },
    { id: "minecraft:grass_block", en: "GRASS", cn: "草方块", phonetic: "/ɡræs/" },
    { id: "minecraft:stone", en: "STONE", cn: "石头", phonetic: "/stoʊn/" },
    { id: "minecraft:cobblestone", en: "COBBLESTONE", cn: "圆石", phonetic: "/ˈkɒblstoʊn/" },
    { id: "minecraft:oak_log", en: "OAK LOG", cn: "橡木原木", phonetic: "/oʊk lɒɡ/" },
    { id: "minecraft:oak_planks", en: "OAK PLANKS", cn: "橡木板", phonetic: "/oʊk plæŋks/" },
    { id: "minecraft:sand", en: "SAND", cn: "沙子", phonetic: "/sænd/" },
    { id: "minecraft:gravel", en: "GRAVEL", cn: "砂砾", phonetic: "/ˈɡrævəl/" },
    { id: "minecraft:crafting_table", en: "CRAFTING TABLE", cn: "工作台", phonetic: "/ˈkræftɪŋ ˈteɪbl/" },
    { id: "minecraft:furnace", en: "FURNACE", cn: "熔炉", phonetic: "/ˈfɜːrnɪs/" },
    { id: "minecraft:chest", en: "CHEST", cn: "箱子", phonetic: "/tʃest/" },
    { id: "minecraft:torch", en: "TORCH", cn: "火把", phonetic: "/tɔːrtʃ/" },
    { id: "minecraft:bed", en: "BED", cn: "床", phonetic: "/bed/" },
    { id: "minecraft:door", en: "DOOR", cn: "门", phonetic: "/dɔːr/" },
    { id: "minecraft:ladder", en: "LADDER", cn: "梯子", phonetic: "/ˈlædər/" },
    { id: "minecraft:glass", en: "GLASS", cn: "玻璃", phonetic: "/ɡlæs/" },
    { id: "minecraft:fence", en: "FENCE", cn: "栅栏", phonetic: "/fens/" },
  ],
};
