// Level 2 - 探索自然 Exploring Nature
export const level2 = {
  name: "Exploring Nature",
  nameCn: "探索自然",
  star: "⭐⭐",
  entities: [
    { id: "minecraft:rabbit", en: "RABBIT", cn: "兔子", phonetic: "/ˈræbɪt/" },
    { id: "minecraft:fox", en: "FOX", cn: "狐狸", phonetic: "/fɒks/" },
    { id: "minecraft:bee", en: "BEE", cn: "蜜蜂", phonetic: "/biː/" },
    { id: "minecraft:dolphin", en: "DOLPHIN", cn: "海豚", phonetic: "/ˈdɒlfɪn/" },
    { id: "minecraft:turtle", en: "TURTLE", cn: "海龟", phonetic: "/ˈtɜːrtl/" },
    { id: "minecraft:squid", en: "SQUID", cn: "鱿鱼", phonetic: "/skwɪd/" },
    { id: "minecraft:bat", en: "BAT", cn: "蝙蝠", phonetic: "/bæt/" },
    { id: "minecraft:parrot", en: "PARROT", cn: "鹦鹉", phonetic: "/ˈpærət/" },
    { id: "minecraft:panda", en: "PANDA", cn: "熊猫", phonetic: "/ˈpændə/" },
    { id: "minecraft:polar_bear", en: "POLAR BEAR", cn: "北极熊", phonetic: "/ˈpoʊlər bɛr/" },
    { id: "minecraft:goat", en: "GOAT", cn: "山羊", phonetic: "/ɡoʊt/" },
    { id: "minecraft:frog", en: "FROG", cn: "青蛙", phonetic: "/frɒɡ/" },
    { id: "minecraft:camel", en: "CAMEL", cn: "骆驼", phonetic: "/ˈkæməl/" },
    { id: "minecraft:sniffer", en: "SNIFFER", cn: "嗅探兽", phonetic: "/ˈsnɪfər/" },
    { id: "minecraft:armadillo", en: "ARMADILLO", cn: "犰狳", phonetic: "/ˌɑːrməˈdɪloʊ/" },
    { id: "minecraft:ocelot", en: "OCELOT", cn: "豹猫", phonetic: "/ˈɒsəlɒt/" },
    { id: "minecraft:salmon", en: "SALMON", cn: "鲑鱼", phonetic: "/ˈsæmən/" },
    { id: "minecraft:cod", en: "COD", cn: "鳕鱼", phonetic: "/kɒd/" },
    { id: "minecraft:tropicalfish", en: "TROPICAL FISH", cn: "热带鱼", phonetic: "/ˈtrɒpɪkəl fɪʃ/" },
  ],
  blocks: [
    { id: "minecraft:ice", en: "ICE", cn: "冰", phonetic: "/aɪs/" },
    { id: "minecraft:snow", en: "SNOW", cn: "雪", phonetic: "/snoʊ/" },
    { id: "minecraft:clay", en: "CLAY", cn: "粘土", phonetic: "/kleɪ/" },
    { id: "minecraft:cactus", en: "CACTUS", cn: "仙人掌", phonetic: "/ˈkæktəs/" },
    { id: "minecraft:pumpkin", en: "PUMPKIN", cn: "南瓜", phonetic: "/ˈpʌmpkɪn/" },
    { id: "minecraft:melon_block", en: "MELON", cn: "西瓜", phonetic: "/ˈmelən/" },
    { id: "minecraft:birch_log", en: "BIRCH LOG", cn: "白桦原木", phonetic: "/bɜːrtʃ lɒɡ/" },
    { id: "minecraft:spruce_log", en: "SPRUCE LOG", cn: "云杉原木", phonetic: "/spruːs lɒɡ/" },
    { id: "minecraft:jungle_log", en: "JUNGLE LOG", cn: "丛林原木", phonetic: "/ˈdʒʌŋɡl lɒɡ/" },
    { id: "minecraft:acacia_log", en: "ACACIA LOG", cn: "金合欢原木", phonetic: "/əˈkeɪʃə lɒɡ/" },
    { id: "minecraft:bamboo_block", en: "BAMBOO", cn: "竹子", phonetic: "/bæmˈbuː/" },
    { id: "minecraft:vine", en: "VINE", cn: "藤蔓", phonetic: "/vaɪn/" },
    { id: "minecraft:lily_pad", en: "LILY PAD", cn: "睡莲", phonetic: "/ˈlɪli pæd/" },
    { id: "minecraft:sunflower", en: "SUNFLOWER", cn: "向日葵", phonetic: "/ˈsʌnflaʊər/" },
    { id: "minecraft:red_flower", en: "FLOWER", cn: "花", phonetic: "/flaʊər/" },
    { id: "minecraft:brown_mushroom", en: "MUSHROOM", cn: "蘑菇", phonetic: "/ˈmʌʃruːm/" },
    { id: "minecraft:sugarcane", en: "SUGAR CANE", cn: "甘蔗", phonetic: "/ˈʃʊɡər keɪn/" },
    { id: "minecraft:hay_block", en: "HAY", cn: "干草", phonetic: "/heɪ/" },
    { id: "minecraft:bookshelf", en: "BOOKSHELF", cn: "书架", phonetic: "/ˈbʊkʃelf/" },
  ],
};
