// Level 2 - 第一周 First Week
export const level2 = {
  name: "First Week",
  nameCn: "第一周",
  star: "⭐⭐",
  entities: [
    { id: "minecraft:villager_v2", en: "VILLAGER", cn: "村民", phonetic: "/ˈvɪlɪdʒər/" },
    { id: "minecraft:iron_golem", en: "IRON GOLEM", cn: "铁傀儡", phonetic: "/ˈaɪərn ˈɡoʊləm/" },
    { id: "minecraft:fox", en: "FOX", cn: "狐狸", phonetic: "/fɒks/" },
    { id: "minecraft:ocelot", en: "OCELOT", cn: "豹猫", phonetic: "/ˈɒsəlɒt/" },
    { id: "minecraft:parrot", en: "PARROT", cn: "鹦鹉", phonetic: "/ˈpærət/" },
    { id: "minecraft:turtle", en: "TURTLE", cn: "海龟", phonetic: "/ˈtɜːrtl/" },
    { id: "minecraft:dolphin", en: "DOLPHIN", cn: "海豚", phonetic: "/ˈdɒlfɪn/" },
    { id: "minecraft:panda", en: "PANDA", cn: "熊猫", phonetic: "/ˈpændə/" },
    { id: "minecraft:goat", en: "GOAT", cn: "山羊", phonetic: "/ɡoʊt/" },
    { id: "minecraft:salmon", en: "SALMON", cn: "鲑鱼", phonetic: "/ˈsæmən/" },
    { id: "minecraft:tropicalfish", en: "TROPICAL FISH", cn: "热带鱼", phonetic: "/ˈtrɒpɪkəl fɪʃ/" },
    { id: "minecraft:witch", en: "WITCH", cn: "女巫", phonetic: "/wɪtʃ/" },
    { id: "minecraft:slime", en: "SLIME", cn: "史莱姆", phonetic: "/slaɪm/" },
    { id: "minecraft:husk", en: "HUSK", cn: "尸壳", phonetic: "/hʌsk/" },
    { id: "minecraft:stray", en: "STRAY", cn: "流浪者", phonetic: "/streɪ/" },
    { id: "minecraft:enderman", en: "ENDERMAN", cn: "末影人", phonetic: "/ˈendərmæn/" },
    { id: "minecraft:phantom", en: "PHANTOM", cn: "幻翼", phonetic: "/ˈfæntəm/" },
    { id: "minecraft:drowned", en: "DROWNED", cn: "溺尸", phonetic: "/draʊnd/" },
  ],
  blocks: [
    { id: "minecraft:gold_ore", en: "GOLD ORE", cn: "金矿石", phonetic: "/ɡoʊld ɔːr/" },
    { id: "minecraft:diamond_ore", en: "DIAMOND ORE", cn: "钻石矿", phonetic: "/ˈdaɪmənd ɔːr/" },
    { id: "minecraft:redstone_ore", en: "REDSTONE ORE", cn: "红石矿", phonetic: "/ˈredˌstoʊn ɔːr/" },
    { id: "minecraft:lapis_ore", en: "LAPIS ORE", cn: "青金石矿", phonetic: "/ˈlæpɪs ɔːr/" },
    { id: "minecraft:emerald_ore", en: "EMERALD ORE", cn: "绿宝石矿", phonetic: "/ˈemərəld ɔːr/" },
    { id: "minecraft:deepslate", en: "DEEPSLATE", cn: "深板岩", phonetic: "/ˈdiːpsleɪt/" },
    { id: "minecraft:iron_block", en: "IRON BLOCK", cn: "铁块", phonetic: "/ˈaɪərn blɒk/" },
    { id: "minecraft:gold_block", en: "GOLD BLOCK", cn: "金块", phonetic: "/ɡoʊld blɒk/" },
    { id: "minecraft:birch_log", en: "BIRCH LOG", cn: "白桦原木", phonetic: "/bɜːrtʃ lɒɡ/" },
    { id: "minecraft:spruce_log", en: "SPRUCE LOG", cn: "云杉原木", phonetic: "/spruːs lɒɡ/" },
    { id: "minecraft:jungle_log", en: "JUNGLE LOG", cn: "丛林原木", phonetic: "/ˈdʒʌŋɡl lɒɡ/" },
    { id: "minecraft:acacia_log", en: "ACACIA LOG", cn: "金合欢原木", phonetic: "/əˈkeɪʃə lɒɡ/" },
    { id: "minecraft:ice", en: "ICE", cn: "冰", phonetic: "/aɪs/" },
    { id: "minecraft:snow", en: "SNOW", cn: "雪", phonetic: "/snoʊ/" },
    { id: "minecraft:cactus", en: "CACTUS", cn: "仙人掌", phonetic: "/ˈkæktəs/" },
    { id: "minecraft:melon_block", en: "MELON", cn: "西瓜", phonetic: "/ˈmelən/" },
    { id: "minecraft:bamboo_block", en: "BAMBOO", cn: "竹子", phonetic: "/bæmˈbuː/" },
    { id: "minecraft:vine", en: "VINE", cn: "藤蔓", phonetic: "/vaɪn/" },
    { id: "minecraft:lily_pad", en: "LILY PAD", cn: "睡莲", phonetic: "/ˈlɪli pæd/" },
    { id: "minecraft:sunflower", en: "SUNFLOWER", cn: "向日葵", phonetic: "/ˈsʌnflaʊər/" },
    { id: "minecraft:hay_block", en: "HAY", cn: "干草", phonetic: "/heɪ/" },
    { id: "minecraft:bookshelf", en: "BOOKSHELF", cn: "书架", phonetic: "/ˈbʊkʃelf/" },
    { id: "minecraft:anvil", en: "ANVIL", cn: "铁砧", phonetic: "/ˈænvɪl/" },
    { id: "minecraft:stonebrick", en: "STONE BRICK", cn: "石砖", phonetic: "/stoʊn brɪk/" },
    { id: "minecraft:brick_block", en: "BRICK", cn: "砖块", phonetic: "/brɪk/" },
    { id: "minecraft:mossy_cobblestone", en: "MOSSY STONE", cn: "苔石", phonetic: "/ˈmɒsi stoʊn/" },
    { id: "minecraft:rail", en: "RAIL", cn: "铁轨", phonetic: "/reɪl/" },
    { id: "minecraft:barrel", en: "BARREL", cn: "木桶", phonetic: "/ˈbærəl/" },
    { id: "minecraft:lantern", en: "LANTERN", cn: "灯笼", phonetic: "/ˈlæntərn/" },
    { id: "minecraft:campfire", en: "CAMPFIRE", cn: "营火", phonetic: "/ˈkæmpfaɪər/" },
    { id: "minecraft:bell", en: "BELL", cn: "钟", phonetic: "/bel/" },
    { id: "minecraft:composter", en: "COMPOSTER", cn: "堆肥桶", phonetic: "/kəmˈpoʊstər/" },
    { id: "minecraft:smoker", en: "SMOKER", cn: "烟熏炉", phonetic: "/ˈsmoʊkər/" },
    { id: "minecraft:stonecutter_block", en: "STONECUTTER", cn: "切石机", phonetic: "/ˈstoʊnˌkʌtər/" },
    { id: "minecraft:grindstone", en: "GRINDSTONE", cn: "砂轮", phonetic: "/ˈɡraɪndstoʊn/" },
    { id: "minecraft:tnt", en: "TNT", cn: "炸药", phonetic: "/tiː en tiː/" },
    { id: "minecraft:obsidian", en: "OBSIDIAN", cn: "黑曜石", phonetic: "/əbˈsɪdiən/" },
    { id: "minecraft:terracotta", en: "TERRACOTTA", cn: "陶瓦", phonetic: "/ˌterəˈkɒtə/" },
    { id: "minecraft:concrete", en: "CONCRETE", cn: "混凝土", phonetic: "/ˈkɒnkriːt/" },
    { id: "minecraft:loom", en: "LOOM", cn: "织布机", phonetic: "/luːm/" },
    { id: "minecraft:lectern", en: "LECTERN", cn: "讲台", phonetic: "/ˈlektərn/" },
    { id: "minecraft:cartography_table", en: "CARTOGRAPHY TABLE", cn: "制图台", phonetic: "/kɑːrˈtɒɡrəfi ˈteɪbl/" },
    { id: "minecraft:fletching_table", en: "FLETCHING TABLE", cn: "制箭台", phonetic: "/ˈfletʃɪŋ ˈteɪbl/" },
    { id: "minecraft:beehive", en: "BEEHIVE", cn: "蜂巢", phonetic: "/ˈbiːhaɪv/" },
    { id: "minecraft:jukebox", en: "JUKEBOX", cn: "唱片机", phonetic: "/ˈdʒuːkbɒks/" },
    { id: "minecraft:note_block", en: "NOTE BLOCK", cn: "音符盒", phonetic: "/noʊt blɒk/" },
    { id: "minecraft:tripwire_hook", en: "TRIPWIRE HOOK", cn: "绊线钩", phonetic: "/ˈtrɪpwaɪər hʊk/" },
    { id: "minecraft:pressure_plate", en: "PRESSURE PLATE", cn: "压力板", phonetic: "/ˈpreʃər pleɪt/" },
    { id: "minecraft:lever", en: "LEVER", cn: "拉杆", phonetic: "/ˈlevər/" },
    { id: "minecraft:button", en: "BUTTON", cn: "按钮", phonetic: "/ˈbʌtən/" },
    { id: "minecraft:dark_oak_log", en: "DARK OAK LOG", cn: "深色橡木原木", phonetic: "/dɑːrk oʊk lɒɡ/" },
    { id: "minecraft:mangrove_log", en: "MANGROVE LOG", cn: "红树原木", phonetic: "/ˈmæŋɡroʊv lɒɡ/" },
    { id: "minecraft:cherry_log", en: "CHERRY LOG", cn: "樱花原木", phonetic: "/ˈtʃeri lɒɡ/" },
  ],
  items: [
    { id: "minecraft:iron_sword", en: "IRON SWORD", cn: "铁剑", phonetic: "/ˈaɪərn sɔːrd/" },
    { id: "minecraft:iron_pickaxe", en: "IRON PICKAXE", cn: "铁镐", phonetic: "/ˈaɪərn ˈpɪkæks/" },
    { id: "minecraft:iron_axe", en: "IRON AXE", cn: "铁斧", phonetic: "/ˈaɪərn æks/" },
    { id: "minecraft:iron_shovel", en: "IRON SHOVEL", cn: "铁锹", phonetic: "/ˈaɪərn ˈʃʌvəl/" },
    { id: "minecraft:iron_hoe", en: "IRON HOE", cn: "铁锄", phonetic: "/ˈaɪərn hoʊ/" },
    { id: "minecraft:iron_helmet", en: "IRON HELMET", cn: "铁头盔", phonetic: "/ˈaɪərn ˈhelmɪt/" },
    { id: "minecraft:iron_chestplate", en: "IRON CHESTPLATE", cn: "铁胸甲", phonetic: "/ˈaɪərn ˈtʃestpleɪt/" },
    { id: "minecraft:iron_leggings", en: "IRON LEGGINGS", cn: "铁护腿", phonetic: "/ˈaɪərn ˈleɡɪŋz/" },
    { id: "minecraft:iron_boots", en: "IRON BOOTS", cn: "铁靴子", phonetic: "/ˈaɪərn buːts/" },
    { id: "minecraft:fishing_rod", en: "FISHING ROD", cn: "钓鱼竿", phonetic: "/ˈfɪʃɪŋ rɒd/" },
    { id: "minecraft:shears", en: "SHEARS", cn: "剪刀", phonetic: "/ʃɪrz/" },
    { id: "minecraft:flint_and_steel", en: "FLINT AND STEEL", cn: "打火石", phonetic: "/flɪnt ænd stiːl/" },
    { id: "minecraft:compass", en: "COMPASS", cn: "指南针", phonetic: "/ˈkʌmpəs/" },
    { id: "minecraft:clock", en: "CLOCK", cn: "时钟", phonetic: "/klɒk/" },
    { id: "minecraft:map", en: "MAP", cn: "地图", phonetic: "/mæp/" },
    { id: "minecraft:book", en: "BOOK", cn: "书", phonetic: "/bʊk/" },
    { id: "minecraft:paper", en: "PAPER", cn: "纸", phonetic: "/ˈpeɪpər/" },
    { id: "minecraft:iron_ingot", en: "IRON INGOT", cn: "铁锭", phonetic: "/ˈaɪərn ˈɪŋɡət/" },
    { id: "minecraft:gold_ingot", en: "GOLD INGOT", cn: "金锭", phonetic: "/ɡoʊld ˈɪŋɡət/" },
    { id: "minecraft:diamond", en: "DIAMOND", cn: "钻石", phonetic: "/ˈdaɪmənd/" },
    { id: "minecraft:emerald", en: "EMERALD", cn: "绿宝石", phonetic: "/ˈemərəld/" },
    { id: "minecraft:cooked_beef", en: "STEAK", cn: "牛排", phonetic: "/steɪk/" },
    { id: "minecraft:cooked_porkchop", en: "PORKCHOP", cn: "猪排", phonetic: "/ˈpɔːrktʃɒp/" },
    { id: "minecraft:cooked_chicken", en: "COOKED CHICKEN", cn: "熟鸡肉", phonetic: "/kʊkt ˈtʃɪkɪn/" },
    { id: "minecraft:cookie", en: "COOKIE", cn: "曲奇", phonetic: "/ˈkʊki/" },
    { id: "minecraft:cake", en: "CAKE", cn: "蛋糕", phonetic: "/keɪk/" },
    { id: "minecraft:milk_bucket", en: "MILK", cn: "牛奶", phonetic: "/mɪlk/" },
    { id: "minecraft:lead", en: "LEAD", cn: "拴绳", phonetic: "/liːd/" },
    { id: "minecraft:saddle", en: "SADDLE", cn: "鞍", phonetic: "/ˈsædl/" },
    { id: "minecraft:name_tag", en: "NAME TAG", cn: "命名牌", phonetic: "/neɪm tæɡ/" },
    { id: "minecraft:gold_sword", en: "GOLDEN SWORD", cn: "金剑", phonetic: "/ˈɡoʊldən sɔːrd/" },
    { id: "minecraft:gold_pickaxe", en: "GOLDEN PICKAXE", cn: "金镐", phonetic: "/ˈɡoʊldən ˈpɪkæks/" },
    { id: "minecraft:leather_helmet", en: "LEATHER HELMET", cn: "皮革头盔", phonetic: "/ˈleðər ˈhelmɪt/" },
    { id: "minecraft:chainmail_helmet", en: "CHAINMAIL HELMET", cn: "锁链头盔", phonetic: "/ˈtʃeɪnmeɪl ˈhelmɪt/" },
    { id: "minecraft:pumpkin_pie", en: "PUMPKIN PIE", cn: "南瓜派", phonetic: "/ˈpʌmpkɪn paɪ/" },
    { id: "minecraft:honey_bottle", en: "HONEY BOTTLE", cn: "蜂蜜瓶", phonetic: "/ˈhʌni ˈbɒtl/" },
    { id: "minecraft:honeycomb", en: "HONEYCOMB", cn: "蜜脾", phonetic: "/ˈhʌnikoʊm/" },
    { id: "minecraft:dye", en: "DYE", cn: "染料", phonetic: "/daɪ/" },
    { id: "minecraft:banner", en: "BANNER", cn: "旗帜", phonetic: "/ˈbænər/" },
    { id: "minecraft:minecart", en: "MINECART", cn: "矿车", phonetic: "/ˈmaɪnkɑːrt/" },
    { id: "minecraft:boat", en: "BOAT", cn: "船", phonetic: "/boʊt/" },
    { id: "minecraft:copper_ingot", en: "COPPER INGOT", cn: "铜锭", phonetic: "/ˈkɒpər ˈɪŋɡət/" },
    { id: "minecraft:raw_iron", en: "RAW IRON", cn: "粗铁", phonetic: "/rɔː ˈaɪərn/" },
    { id: "minecraft:raw_gold", en: "RAW GOLD", cn: "粗金", phonetic: "/rɔː ɡoʊld/" },
    { id: "minecraft:raw_copper", en: "RAW COPPER", cn: "粗铜", phonetic: "/rɔː ˈkɒpər/" },
    { id: "minecraft:dried_kelp", en: "DRIED KELP", cn: "干海带", phonetic: "/draɪd kelp/" },
    { id: "minecraft:suspicious_stew", en: "SUSPICIOUS STEW", cn: "迷之炖菜", phonetic: "/səˈspɪʃəs stjuː/" },
  ],
};
