// Level 3 - 探索期 Exploration
export const level3 = {
  name: "Exploration",
  nameCn: "探索期",
  star: "⭐⭐⭐",
  entities: [
    { id: "minecraft:polar_bear", en: "POLAR BEAR", cn: "北极熊", phonetic: "/ˈpoʊlər bɛr/" },
    { id: "minecraft:llama", en: "LLAMA", cn: "羊驼", phonetic: "/ˈlɑːmə/" },
    { id: "minecraft:wandering_trader", en: "TRADER", cn: "商人", phonetic: "/ˈtreɪdər/" },
    { id: "minecraft:frog", en: "FROG", cn: "青蛙", phonetic: "/frɒɡ/" },
    { id: "minecraft:camel", en: "CAMEL", cn: "骆驼", phonetic: "/ˈkæməl/" },
    { id: "minecraft:sniffer", en: "SNIFFER", cn: "嗅探兽", phonetic: "/ˈsnɪfər/" },
    { id: "minecraft:armadillo", en: "ARMADILLO", cn: "犰狳", phonetic: "/ˌɑːrməˈdɪloʊ/" },
    { id: "minecraft:axolotl", en: "AXOLOTL", cn: "美西螈", phonetic: "/ˈæksəlɒtl/" },
    { id: "minecraft:glow_squid", en: "GLOW SQUID", cn: "发光鱿鱼", phonetic: "/ɡloʊ skwɪd/" },
    { id: "minecraft:cave_spider", en: "CAVE SPIDER", cn: "洞穴蜘蛛", phonetic: "/keɪv ˈspaɪdər/" },
    { id: "minecraft:silverfish", en: "SILVERFISH", cn: "蠹虫", phonetic: "/ˈsɪlvərfɪʃ/" },
    { id: "minecraft:pillager", en: "PILLAGER", cn: "掠夺者", phonetic: "/ˈpɪlɪdʒər/" },
    { id: "minecraft:ravager", en: "RAVAGER", cn: "劫掠兽", phonetic: "/ˈrævɪdʒər/" },
    { id: "minecraft:evoker", en: "EVOKER", cn: "唤魔者", phonetic: "/ɪˈvoʊkər/" },
    { id: "minecraft:vex", en: "VEX", cn: "恼鬼", phonetic: "/veks/" },
    { id: "minecraft:guardian", en: "GUARDIAN", cn: "守卫者", phonetic: "/ˈɡɑːrdiən/" },
    { id: "minecraft:snow_golem", en: "SNOW GOLEM", cn: "雪傀儡", phonetic: "/snoʊ ˈɡoʊləm/" },
    { id: "minecraft:mule", en: "MULE", cn: "骡子", phonetic: "/mjuːl/" },
  ],
  blocks: [
    { id: "minecraft:diamond_block", en: "DIAMOND BLOCK", cn: "钻石块", phonetic: "/ˈdaɪmənd blɒk/" },
    { id: "minecraft:enchanting_table", en: "ENCHANTING TABLE", cn: "附魔台", phonetic: "/ɪnˈtʃæntɪŋ ˈteɪbl/" },
    { id: "minecraft:brewing_stand", en: "BREWING STAND", cn: "酿造台", phonetic: "/ˈbruːɪŋ stænd/" },
    { id: "minecraft:cauldron", en: "CAULDRON", cn: "炼药锅", phonetic: "/ˈkɔːldrən/" },
    { id: "minecraft:smithing_table", en: "SMITHING TABLE", cn: "锻造台", phonetic: "/ˈsmɪθɪŋ ˈteɪbl/" },
    { id: "minecraft:blast_furnace", en: "BLAST FURNACE", cn: "高炉", phonetic: "/blæst ˈfɜːrnɪs/" },
    { id: "minecraft:soul_sand", en: "SOUL SAND", cn: "灵魂沙", phonetic: "/soʊl sænd/" },
    { id: "minecraft:mob_spawner", en: "SPAWNER", cn: "刷怪笼", phonetic: "/ˈspɔːnər/" },
    { id: "minecraft:cobweb", en: "COBWEB", cn: "蜘蛛网", phonetic: "/ˈkɒbweb/" },
    { id: "minecraft:bone_block", en: "BONE BLOCK", cn: "骨块", phonetic: "/boʊn blɒk/" },
    { id: "minecraft:target", en: "TARGET", cn: "标靶", phonetic: "/ˈtɑːrɡɪt/" },
    { id: "minecraft:piston", en: "PISTON", cn: "活塞", phonetic: "/ˈpɪstən/" },
    { id: "minecraft:sticky_piston", en: "STICKY PISTON", cn: "粘性活塞", phonetic: "/ˈstɪki ˈpɪstən/" },
    { id: "minecraft:redstone_block", en: "REDSTONE BLOCK", cn: "红石块", phonetic: "/ˈredˌstoʊn blɒk/" },
    { id: "minecraft:repeater", en: "REPEATER", cn: "中继器", phonetic: "/rɪˈpiːtər/" },
    { id: "minecraft:comparator", en: "COMPARATOR", cn: "比较器", phonetic: "/kəmˈpærətər/" },
    { id: "minecraft:observer", en: "OBSERVER", cn: "侦测器", phonetic: "/əbˈzɜːrvər/" },
    { id: "minecraft:hopper", en: "HOPPER", cn: "漏斗", phonetic: "/ˈhɒpər/" },
    { id: "minecraft:dropper", en: "DROPPER", cn: "投掷器", phonetic: "/ˈdrɒpər/" },
    { id: "minecraft:dispenser", en: "DISPENSER", cn: "发射器", phonetic: "/dɪˈspensər/" },
    { id: "minecraft:daylight_detector", en: "DAYLIGHT SENSOR", cn: "阳光传感器", phonetic: "/ˈdeɪlaɪt ˈsensər/" },
    { id: "minecraft:amethyst_block", en: "AMETHYST", cn: "紫水晶", phonetic: "/ˈæməθɪst/" },
    { id: "minecraft:dripstone_block", en: "DRIPSTONE", cn: "滴水石", phonetic: "/ˈdrɪpstoʊn/" },
    { id: "minecraft:moss_block", en: "MOSS", cn: "苔藓", phonetic: "/mɒs/" },
    { id: "minecraft:tuff", en: "TUFF", cn: "凝灰岩", phonetic: "/tʌf/" },
    { id: "minecraft:copper_block", en: "COPPER BLOCK", cn: "铜块", phonetic: "/ˈkɒpər blɒk/" },
    { id: "minecraft:prismarine", en: "PRISMARINE", cn: "海晶石", phonetic: "/ˈprɪzməriːn/" },
    { id: "minecraft:sea_lantern", en: "SEA LANTERN", cn: "海晶灯", phonetic: "/siː ˈlæntərn/" },
    { id: "minecraft:sponge", en: "SPONGE", cn: "海绵", phonetic: "/spʌndʒ/" },
    { id: "minecraft:flowering_azalea", en: "FLOWERING AZALEA", cn: "盛开的杜鹃花", phonetic: "/ˈflaʊərɪŋ əˈzeɪliə/" },
    { id: "minecraft:glow_lichen", en: "GLOW LICHEN", cn: "发光地衣", phonetic: "/ɡloʊ ˈlaɪkən/" },
    { id: "minecraft:pointed_dripstone", en: "POINTED DRIPSTONE", cn: "滴水石锥", phonetic: "/ˈpɔɪntɪd ˈdrɪpstoʊn/" },
    { id: "minecraft:coral_block", en: "CORAL", cn: "珊瑚", phonetic: "/ˈkɒrəl/" },
    { id: "minecraft:chain", en: "CHAIN", cn: "锁链", phonetic: "/tʃeɪn/" },
    { id: "minecraft:lightning_rod", en: "LIGHTNING ROD", cn: "避雷针", phonetic: "/ˈlaɪtnɪŋ rɒd/" },
    { id: "minecraft:candle", en: "CANDLE", cn: "蜡烛", phonetic: "/ˈkændl/" },
    { id: "minecraft:ender_chest", en: "ENDER CHEST", cn: "末影箱", phonetic: "/ˈendər tʃest/" },
    { id: "minecraft:armor_stand", en: "ARMOR STAND", cn: "盔甲架", phonetic: "/ˈɑːrmər stænd/" },
    { id: "minecraft:decorated_pot", en: "DECORATED POT", cn: "彩陶罐", phonetic: "/ˈdekəreɪtɪd pɒt/" },
    { id: "minecraft:chiseled_bookshelf", en: "CHISELED BOOKSHELF", cn: "雕纹书架", phonetic: "/ˈtʃɪzəld ˈbʊkʃelf/" },
    { id: "minecraft:suspicious_sand", en: "SUSPICIOUS SAND", cn: "可疑的沙子", phonetic: "/səˈspɪʃəs sænd/" },
    { id: "minecraft:suspicious_gravel", en: "SUSPICIOUS GRAVEL", cn: "可疑的砂砾", phonetic: "/səˈspɪʃəs ˈɡrævəl/" },
  ],
  items: [
    { id: "minecraft:diamond_sword", en: "DIAMOND SWORD", cn: "钻石剑", phonetic: "/ˈdaɪmənd sɔːrd/" },
    { id: "minecraft:diamond_pickaxe", en: "DIAMOND PICKAXE", cn: "钻石镐", phonetic: "/ˈdaɪmənd ˈpɪkæks/" },
    { id: "minecraft:diamond_axe", en: "DIAMOND AXE", cn: "钻石斧", phonetic: "/ˈdaɪmənd æks/" },
    { id: "minecraft:diamond_shovel", en: "DIAMOND SHOVEL", cn: "钻石锹", phonetic: "/ˈdaɪmənd ˈʃʌvəl/" },
    { id: "minecraft:diamond_helmet", en: "DIAMOND HELMET", cn: "钻石头盔", phonetic: "/ˈdaɪmənd ˈhelmɪt/" },
    { id: "minecraft:diamond_chestplate", en: "DIAMOND CHESTPLATE", cn: "钻石胸甲", phonetic: "/ˈdaɪmənd ˈtʃestpleɪt/" },
    { id: "minecraft:diamond_leggings", en: "DIAMOND LEGGINGS", cn: "钻石护腿", phonetic: "/ˈdaɪmənd ˈleɡɪŋz/" },
    { id: "minecraft:diamond_boots", en: "DIAMOND BOOTS", cn: "钻石靴子", phonetic: "/ˈdaɪmənd buːts/" },
    { id: "minecraft:crossbow", en: "CROSSBOW", cn: "弩", phonetic: "/ˈkrɒsboʊ/" },
    { id: "minecraft:spyglass", en: "SPYGLASS", cn: "望远镜", phonetic: "/ˈspaɪɡlæs/" },
    { id: "minecraft:golden_apple", en: "GOLDEN APPLE", cn: "金苹果", phonetic: "/ˈɡoʊldən ˈæpl/" },
    { id: "minecraft:potion", en: "POTION", cn: "药水", phonetic: "/ˈpoʊʃən/" },
    { id: "minecraft:ender_pearl", en: "ENDER PEARL", cn: "末影珍珠", phonetic: "/ˈendər pɜːrl/" },
    { id: "minecraft:experience_bottle", en: "EXPERIENCE BOTTLE", cn: "经验瓶", phonetic: "/ɪkˈspɪriəns ˈbɒtl/" },
    { id: "minecraft:enchanted_book", en: "ENCHANTED BOOK", cn: "附魔书", phonetic: "/ɪnˈtʃæntɪd bʊk/" },
    { id: "minecraft:trident", en: "TRIDENT", cn: "三叉戟", phonetic: "/ˈtraɪdənt/" },
    { id: "minecraft:pufferfish", en: "PUFFERFISH", cn: "河豚", phonetic: "/ˈpʌfərfɪʃ/" },
    { id: "minecraft:slime_ball", en: "SLIME BALL", cn: "粘液球", phonetic: "/slaɪm bɔːl/" },
    { id: "minecraft:redstone", en: "REDSTONE", cn: "红石", phonetic: "/ˈredˌstoʊn/" },
    { id: "minecraft:lapis_lazuli", en: "LAPIS LAZULI", cn: "青金石", phonetic: "/ˈlæpɪs ˈlæzjʊli/" },
    { id: "minecraft:glowstone_dust", en: "GLOWSTONE DUST", cn: "荧石粉", phonetic: "/ˈɡloʊstoʊn dʌst/" },
    { id: "minecraft:brush", en: "BRUSH", cn: "刷子", phonetic: "/brʌʃ/" },
    { id: "minecraft:goat_horn", en: "GOAT HORN", cn: "山羊角", phonetic: "/ɡoʊt hɔːrn/" },
    { id: "minecraft:glow_ink_sac", en: "GLOW INK SAC", cn: "荧光墨囊", phonetic: "/ɡloʊ ɪŋk sæk/" },
    { id: "minecraft:amethyst_shard", en: "AMETHYST SHARD", cn: "紫水晶碎片", phonetic: "/ˈæməθɪst ʃɑːrd/" },
    { id: "minecraft:glass_bottle", en: "GLASS BOTTLE", cn: "玻璃瓶", phonetic: "/ɡlæs ˈbɒtl/" },
    { id: "minecraft:spider_eye", en: "SPIDER EYE", cn: "蜘蛛眼", phonetic: "/ˈspaɪdər aɪ/" },
    { id: "minecraft:fermented_spider_eye", en: "FERMENTED SPIDER EYE", cn: "发酵蜘蛛眼", phonetic: "/fərˈmentɪd ˈspaɪdər aɪ/" },
    { id: "minecraft:phantom_membrane", en: "PHANTOM MEMBRANE", cn: "幻翼膜", phonetic: "/ˈfæntəm ˈmembreɪn/" },
    { id: "minecraft:rabbit_foot", en: "RABBIT FOOT", cn: "兔子脚", phonetic: "/ˈræbɪt fʊt/" },
    { id: "minecraft:tipped_arrow", en: "TIPPED ARROW", cn: "药箭", phonetic: "/tɪpt ˈæroʊ/" },
    { id: "minecraft:splash_potion", en: "SPLASH POTION", cn: "喷溅药水", phonetic: "/splæʃ ˈpoʊʃən/" },
    { id: "minecraft:lingering_potion", en: "LINGERING POTION", cn: "滞留药水", phonetic: "/ˈlɪŋɡərɪŋ ˈpoʊʃən/" },
    { id: "minecraft:prismarine_shard", en: "PRISMARINE SHARD", cn: "海晶碎片", phonetic: "/ˈprɪzməriːn ʃɑːrd/" },
    { id: "minecraft:prismarine_crystals", en: "PRISMARINE CRYSTALS", cn: "海晶砂粒", phonetic: "/ˈprɪzməriːn ˈkrɪstlz/" },
  ],
};
