// Level 4 - 勇者战斗 Brave Fighter
export const level4 = {
  name: "Brave Fighter",
  nameCn: "勇者战斗",
  star: "⭐⭐⭐⭐",
  entities: [
    { id: "minecraft:zombie", en: "ZOMBIE", cn: "僵尸", phonetic: "/ˈzɒmbi/" },
    { id: "minecraft:skeleton", en: "SKELETON", cn: "骷髅", phonetic: "/ˈskelɪtən/" },
    { id: "minecraft:creeper", en: "CREEPER", cn: "苦力怕", phonetic: "/ˈkriːpər/" },
    { id: "minecraft:spider", en: "SPIDER", cn: "蜘蛛", phonetic: "/ˈspaɪdər/" },
    { id: "minecraft:enderman", en: "ENDERMAN", cn: "末影人", phonetic: "/ˈendərmæn/" },
    { id: "minecraft:witch", en: "WITCH", cn: "女巫", phonetic: "/wɪtʃ/" },
    { id: "minecraft:slime", en: "SLIME", cn: "史莱姆", phonetic: "/slaɪm/" },
    { id: "minecraft:phantom", en: "PHANTOM", cn: "幻翼", phonetic: "/ˈfæntəm/" },
    { id: "minecraft:drowned", en: "DROWNED", cn: "溺尸", phonetic: "/draʊnd/" },
    { id: "minecraft:husk", en: "HUSK", cn: "尸壳", phonetic: "/hʌsk/" },
    { id: "minecraft:stray", en: "STRAY", cn: "流浪者", phonetic: "/streɪ/" },
    { id: "minecraft:pillager", en: "PILLAGER", cn: "掠夺者", phonetic: "/ˈpɪlɪdʒər/" },
    { id: "minecraft:ravager", en: "RAVAGER", cn: "劫掠兽", phonetic: "/ˈrævɪdʒər/" },
    { id: "minecraft:guardian", en: "GUARDIAN", cn: "守卫者", phonetic: "/ˈɡɑːrdiən/" },
    { id: "minecraft:cave_spider", en: "CAVE SPIDER", cn: "洞穴蜘蛛", phonetic: "/keɪv ˈspaɪdər/" },
    { id: "minecraft:silverfish", en: "SILVERFISH", cn: "蠹虫", phonetic: "/ˈsɪlvərfɪʃ/" },
    { id: "minecraft:vex", en: "VEX", cn: "恼鬼", phonetic: "/veks/" },
    { id: "minecraft:evoker", en: "EVOKER", cn: "唤魔者", phonetic: "/ɪˈvoʊkər/" },
  ],
  blocks: [
    { id: "minecraft:tnt", en: "TNT", cn: "炸药", phonetic: "/tiː en tiː/" },
    { id: "minecraft:enchanting_table", en: "ENCHANTING TABLE", cn: "附魔台", phonetic: "/ɪnˈtʃæntɪŋ ˈteɪbl/" },
    { id: "minecraft:brewing_stand", en: "BREWING STAND", cn: "酿造台", phonetic: "/ˈbruːɪŋ stænd/" },
    { id: "minecraft:cauldron", en: "CAULDRON", cn: "炼药锅", phonetic: "/ˈkɔːldrən/" },
    { id: "minecraft:mob_spawner", en: "SPAWNER", cn: "刷怪笼", phonetic: "/ˈspɔːnər/" },
    { id: "minecraft:cobweb", en: "COBWEB", cn: "蜘蛛网", phonetic: "/ˈkɒbweb/" },
    { id: "minecraft:soul_sand", en: "SOUL SAND", cn: "灵魂沙", phonetic: "/soʊl sænd/" },
    { id: "minecraft:end_stone", en: "END STONE", cn: "末地石", phonetic: "/end stoʊn/" },
    { id: "minecraft:bone_block", en: "BONE BLOCK", cn: "骨块", phonetic: "/boʊn blɒk/" },
    { id: "minecraft:target", en: "TARGET", cn: "标靶", phonetic: "/ˈtɑːrɡɪt/" },
    { id: "minecraft:bell", en: "BELL", cn: "钟", phonetic: "/bel/" },
    { id: "minecraft:respawn_anchor", en: "RESPAWN ANCHOR", cn: "重生锚", phonetic: "/riːˈspɔːn ˈæŋkər/" },
  ],
};
